[Feat] Create Notion Database From RocketChat For Properties Includes Configuration
RocketChat/Apps.Notion pull request #15
Opened 2023-06-19 07:52 UTC by Nabhag8848

## Issue(s) 
- Closes #6 and addition to #14 

## Acceptance Criteria fulfillment

- [x] Created Dispatch Actions for Property Type Select, MultiSelect, Formula and Number
- [x] Updates Modal as Per the Selection of Property Type and Has Additional Configuration Elements When Required.
- [x] Handle Missing Properties With and Without Having Configuration [ViewErrors]
- [x] Handle Duplicate Property Name with ViewErrors.
- [x] Fix Return type of CreateNotionDatabase method under NotionSDK to have INotionDatabase as Return Type.
- [x] Configured Notification of Creation of Database iin Channel to Have the Table as Attachments showing the Database created propertyName and PropertyType.
## Proposed changes (including videos or screenshots)

## Further comments

2023-07-09 15:10 UTC, samad-yar-khan requested changes
@Nabhag8848  Requested some changes.

2023-07-09 15:10 UTC, samad-yar-khan commented on enum/modals/common/NotionProperties.ts
> +    SHEKEL = "shekel",
@Nabhag8848  It may be hard to maintain these if there are changes in notion itself.

2023-07-09 15:10 UTC, samad-yar-khan commented on src/handlers/ExecuteBlockActionHandler.ts
> +                    : null;
@Nabhag8848 Can we make this more readable ?

2023-07-09 15:10 UTC, samad-yar-khan commented on src/handlers/ExecuteBlockActionHandler.ts
> +        // when there is no other state and the value is empty
@Nabhag8848  instead of adding these comments, we can just make these conditions as variables themselves. Comments get outdated with every change. Working code however is always the source of truth. 

```
noOtherStateAndEmptyValue = !value && inputElementState;
if(noOtherStateAndEmptyValue ){
 ....
}

nullStateAndCharEntered =  !inputElementState;
if (nullStateAndCharEntered ){
...
}
```

This will also make sure that your condition also goes as per the actual logic and not some random control flow guided by comments.

2023-07-09 15:10 UTC, samad-yar-khan commented on src/handlers/ExecuteBlockActionHandler.ts
> +
@Nabhag8848  Same over here. Conditions can be more concretely stored in variables to improve code maintainability. 
```
if (x>1  && y <2){
...
} 

```
is harder to maintain than

```
conditionExplained = (x>1  && y <2)
if(conditionExplained ){
...
}
```

2023-07-10 06:52 UTC, Nabhag8848 commented on enum/modals/common/NotionProperties.ts
> +    SHEKEL = "shekel",
Yep, @samad-yar-khan  pretty hard. I just check out the changelog and there are changes to it on 3 different releases before. 
1. Between [April - May-2023](https://developers.notion.com/page/changelog#april-18---may-1-2023)
2. Between [Oct-Nov-2022](https://developers.notion.com/page/changelog#october-25---november-7-2022)
3. In [July 2021](https://developers.notion.com/page/changelog#july-26-2021) 

Notion doesn't provide an endpoint to retrieve the available format of Number, format/available value for Notion types having configuration.

Is there any other way we can improve this and make it more managable? i think in this case enum would be more managable as, if there are changes we just need to add the change in enum folder.

2023-07-11 10:31 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
Untitled pageName was causing an UnHandledPromiseRejection in Server which i had fixed later, but as we are making changes i did fix this here.

2023-07-11 10:33 UTC, Nabhag8848 commented on enum/CommandParam.ts
>  }
Made the sub command param to `db` which was discussed previously.

2023-07-11 11:23 UTC, Nabhag8848 commented on src/handlers/ExecuteBlockActionHandler.ts
> +                    ? propertyTypeSelected
Fixed Variable Naming.

2023-07-11 11:24 UTC, Nabhag8848 commented on src/handlers/ExecuteBlockActionHandler.ts
>                          this.handlePropertyTypeSelectAction(
Fixed Variable Naming

2023-07-11 11:25 UTC, Nabhag8848 commented on src/handlers/ExecuteBlockActionHandler.ts
> +                    : null;
yep, done with this one.

2023-07-17 17:33 UTC, merged