[Feat] Create Notion Record From RC
RocketChat/Apps.Notion pull request #22
Opened 2023-08-02 05:27 UTC by Nabhag8848

## Issue(s) 
- Closes #10 

## Acceptance Criteria fulfillment

## Proposed changes (including videos or screenshots)

## Further comments

2023-08-21 18:29 UTC, samad-yar-khan requested changes
@Nabhag8848 left some comments

2023-08-21 18:29 UTC, samad-yar-khan commented on enum/modals/NotionPageOrRecord.ts
> -    ADD_PROPERTY_BUTTON_TEXT = "Add Property",
@Nabhag8848  Are these not needed anymore ?

2023-08-21 18:29 UTC, samad-yar-khan commented on src/handlers/ExecuteViewSubmitHandler.ts
> +        const missingObject = {};
@Nabhag8848  empty constant missing object ?

2023-08-21 18:29 UTC, samad-yar-khan commented on src/handlers/ExecuteViewSubmitHandler.ts
> +                ] = `Please Provide ${titleViewError}`;
@Nabhag8848  you are updating a constant

2023-08-22 06:01 UTC, Nabhag8848 commented on enum/modals/NotionPageOrRecord.ts
> -    ADD_PROPERTY_BUTTON_TEXT = "Add Property",
Nope! these are not needed as we had transition to new implementation. before it was having add and remove but now we just get all the components as user selects notion table.

2023-08-22 06:14 UTC, Nabhag8848 commented on src/handlers/ExecuteViewSubmitHandler.ts
> +                ] = `Please Provide ${titleViewError}`;
I have used assignment immutablity in this case. **const missingObject = { }** is making sure reference to that object doesn't change. 
Just shared the below example showing what i mean.
we can see object1 has also been changed due to change in missingObject as we have a constant reference when changing its changing the existing object not the referrence.

![Screenshot from 2023-08-22 11-34-29](https://github.com/RocketChat/Apps.Notion/assets/65061890/d9fa0f3f-d14a-478b-ad26-f046b25158e2)

2023-08-22 06:29 UTC, Nabhag8848 commented on src/handlers/ExecuteViewSubmitHandler.ts
> +        const missingObject = {};
Renamed to **missingPropObject** to make it more meaningful. its being used for view errors when user misses the required property to input.
Related to https://github.com/RocketChat/Apps.Notion/pull/22#discussion_r1301033427

2023-08-30 13:04 UTC, merged