[ Feat ]: Removed emojis from the app
RocketChat/Apps.Notion pull request #40
Opened 2024-01-19 13:48 UTC by brf153

## Issue(s) 

closes #31 

## Acceptance Criteria fulfillment

- [x] Reported the emojis in the issue section 
- [x] Removed the emojis from the code

## Proposed changes (including videos or screenshots)
https://github.com/RocketChat/Apps.Notion/assets/107868772/78858827-df9e-4b94-8a60-e3c6bce51e10

## Further comments

@Nabhag8848 I could not get the code for the "more" dropdown menu.
![Screenshot from 2024-01-19 19-02-16](https://github.com/RocketChat/Apps.Notion/assets/107868772/bf85bdbd-6a6b-4653-bf98-496e47f76bfc)

2024-01-19 13:58 UTC, Nabhag8848 commented
Find it here
https://github.com/RocketChat/Apps.Notion/blob/main/i18n%2Fen.json

2024-01-19 14:06 UTC, brf153 commented
@Nabhag8848 I have removed the emojis from the i18n files. Still the emoji is there in the menu dropdown

2024-01-19 14:07 UTC, Nabhag8848 commented
> @Nabhag8848 I have removed the emojis from the i18n files. Still the emoji is there in the menu dropdown

Refresh Rocketchat it will not show up anymore.

2024-01-19 14:07 UTC, brf153 commented
![Screenshot from 2024-01-19 19-37-09](https://github.com/RocketChat/Apps.Notion/assets/107868772/754c618f-6bac-4a4b-89fc-65544ce3029a)
![Screenshot from 2024-01-19 19-37-02](https://github.com/RocketChat/Apps.Notion/assets/107868772/9a3e3507-b556-4cff-a306-13904e8088aa)

2024-01-19 14:08 UTC, brf153 commented
> > @Nabhag8848 I have removed the emojis from the i18n files. Still the emoji is there in the menu dropdown
> 
> Refresh Rocketchat it will not show up anymore.

Yeah my bad it is not showing after refreshing the page.
![Screenshot from 2024-01-19 19-38-06](https://github.com/RocketChat/Apps.Notion/assets/107868772/da11b504-17b2-4959-9b12-26b53525be23)

2024-01-19 14:09 UTC, brf153 commented
I think I have removed all the emojis

2024-01-19 14:09 UTC, Nabhag8848 commented
> Find it here
> https://github.com/RocketChat/Apps.Notion/blob/main/i18n%2Fen.json
> 
> @brf153 
> learn about how apps uses i18n translation.
> 
> Can you open up the Modal 
> /notion create
> and see the dropdown if there are no emojis fix that cause we need there to differentiate between page and db.
>

2024-01-19 14:09 UTC, Nabhag8848 commented
> Find it here
> https://github.com/RocketChat/Apps.Notion/blob/main/i18n%2Fen.json
> 
> @brf153 
> learn about how apps uses i18n translation.
> 
> Can you open up the Modal 
> /notion create db
> and see the dropdown if there are no emojis fix that cause we need there to differentiate between page and db.
> 

edited this check: i meant
 /notion create

2024-01-19 14:10 UTC, brf153 commented
![Screenshot from 2024-01-19 19-39-55](https://github.com/RocketChat/Apps.Notion/assets/107868772/9ae301d1-0b07-484f-aafb-525f83af2b22)
![Screenshot from 2024-01-19 19-39-50](https://github.com/RocketChat/Apps.Notion/assets/107868772/a3909351-df6d-4680-976f-edd6eef29c88)

2024-01-19 14:17 UTC, Nabhag8848 commented
> `see the dropdown if there are no emojis fix that cause we need there to differentiate between page and db.` I did not get this line.

Feature 6 under Demo:

https://github.com/Nabhag8848/Google-Summer-of-Code

See those two videos on that same modal when we select Page, Modal doesn't change to include other components as when we select page it is meant to create subpage within notion but in case when we select db ( option with pile of books 📚 it will update the modal to include other components as it this time it is meant to create record or row in a notion table.

2024-01-19 14:21 UTC, brf153 commented
Oki so, should I add the page emoji in front of pages and books emoji in front of database?

2024-01-19 14:23 UTC, Nabhag8848 commented
> Oki so, should I add the page emoji in front of pages and books emoji in front of database?

https://github.com/RocketChat/Apps.Notion/issues/37#issuecomment-1898823965

2024-01-19 14:43 UTC, brf153 commented
@Nabhag8848 I have added emoji:boolean in the function which will check whether the emoji needs to be rendered or not
![Screenshot from 2024-01-19 20-10-27](https://github.com/RocketChat/Apps.Notion/assets/107868772/0a02622d-9810-42fd-996e-13ac0ea6f850)
![Screenshot from 2024-01-19 20-10-09](https://github.com/RocketChat/Apps.Notion/assets/107868772/32464ba6-8ebf-438b-aac6-0e7a2088f285)

2024-01-21 07:17 UTC, brf153 commented
@Nabhag8848 is something left to be done?

2024-01-21 07:19 UTC, Nabhag8848 commented
> @Nabhag8848 is something left to be done?

Will review and test on my end and will let you know.

2024-01-21 07:20 UTC, brf153 commented
Oki

2024-01-23 05:52 UTC, Nabhag8848 commented
Some breaking changes: 

- When Selecting Database in `/notion create` We are showing Emojis in layout: remove
<img width="609" alt="Fix2" src="https://github.com/RocketChat/Apps.Notion/assets/65061890/50cf4bc8-43fa-4d3a-ab90-fc1ec2610f05">

- Missed out 🚫  under `/enum/OAuth2.ts` and `/src/handlers/ExecuteViewSubmitHandler.ts`,  just search "🚫" under IDE, Note: we don't need to remove it from `webhook.ts` folder as it is for AuthTemplate.

2024-01-23 05:59 UTC, brf153 commented
@Nabhag8848 I will fix this right now

2024-01-23 06:10 UTC, Nabhag8848 requested changes
Made Some Changes Comments.

2024-01-23 06:10 UTC, Nabhag8848 commented on README.md
- oops, i believe you made removed from documentation which is not needed.

2024-01-23 06:10 UTC, Nabhag8848 commented on enum/OAuth2.ts
>      CREDENTIALS_MISSING_USER = `🚫 Something Went Wrong, Please Contact the Admin!`,
Remove 🚫

2024-01-23 06:10 UTC, Nabhag8848 commented on src/endpoints/webhook.ts
> -            `👋 Connected to ${response.workspace_name}❗`,
Add 👋 as it is AuthPageTemplate as we discussed earlier.

2024-01-23 06:10 UTC, Nabhag8848 commented on src/handlers/ExecuteViewSubmitHandler.ts
>              message = `🚫 Something went wrong while creating page in **${workspace_name}**.`;
Remove 🚫. there are several others in same file remove all of them.

2024-01-23 06:10 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +    private returnPage(name: string, page_id: string, emoji: boolean): IPage {
can we make emoji parameter default value as false to avoid passing when we don't need emojis.

2024-01-23 06:10 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +    private async getDatabaseObjectFromResults(item, emoji:boolean): Promise<IDatabase> {
Same here: Emoji default value as false and make necessary changes whereever you are calling this function.

2024-01-23 06:28 UTC, brf153 commented on src/lib/NotionSDK.ts
> +    private returnPage(name: string, page_id: string, emoji: boolean): IPage {
oki

2024-01-23 06:29 UTC, brf153 commented on src/handlers/ExecuteViewSubmitHandler.ts
>              message = `🚫 Something went wrong while creating page in **${workspace_name}**.`;
I will try to remove it from wherever it is required. I don't know why but my vs code search does not show any data when I search for "🚫"

2024-01-23 06:29 UTC, brf153 commented on src/endpoints/webhook.ts
> -            `👋 Connected to ${response.workspace_name}❗`,
oki

2024-01-23 06:30 UTC, brf153 commented on src/lib/NotionSDK.ts
> +    private async getDatabaseObjectFromResults(item, emoji:boolean): Promise<IDatabase> {
oki

2024-01-23 06:30 UTC, brf153 commented on README.md
Should I add the emojis in the documentation?

2024-01-23 06:50 UTC, Nabhag8848 commented on README.md
yep

2024-01-23 06:51 UTC, brf153 commented
@Nabhag8848 I have made the changes

2024-01-23 08:04 UTC, brf153 commented
@Nabhag8848 

https://github.com/RocketChat/Apps.Notion/assets/107868772/1b12ae7b-3a86-4d8b-921d-2dae9f9b0941

2024-01-23 08:07 UTC, brf153 commented
I will also remove the emojis from the dialogBox which appears after the /notion create command

2024-01-23 08:43 UTC, brf153 commented
![Screenshot from 2024-01-23 14-12-14](https://github.com/RocketChat/Apps.Notion/assets/107868772/10a2e7a0-c7e1-492b-8509-7fb372af8e11)
in this pic, I am also removing the emoji
![Screenshot from 2024-01-23 14-12-55](https://github.com/RocketChat/Apps.Notion/assets/107868772/05a60633-b69d-431c-a381-5deeca3e6f1c)

2024-01-23 09:06 UTC, brf153 commented
I have made the changes
![Screenshot from 2024-01-23 14-36-23](https://github.com/RocketChat/Apps.Notion/assets/107868772/0ab8422b-4260-4816-9197-f166bcb37372)

2024-01-25 07:08 UTC, Nabhag8848 commented on src/handlers/ExecuteViewSubmitHandler.ts
> +        }
I believe, you overriding this due to when sending message to channel it was showing 📚.  can't directly we can have `const databasename = info.name.replace("📚","");` in line` 504`. mention below. so we don't need to have this `newDatabase` object

```suggestion
        
```

2024-01-25 07:09 UTC, Nabhag8848 commented on src/handlers/ExecuteViewSubmitHandler.ts
>              const databasename = info.name;
Here, as i mentioned above.
```suggestion
            const databasename = info.name.replace("📚","");
```

2024-01-25 07:14 UTC, Nabhag8848 commented on src/helper/getSelectDatabaseLayout.ts
> +    const databaseNameWithoutEmoji = database_name.replace("📚 ", "")
We can directly replace emoji in `database_name` variable to avoid creating new variable. 

```
line 16: const database_name = properties.name.replace("📚 ", "");
```

```suggestion
```

2024-01-25 07:21 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +                false
- Previously we made a emoji param default value false so that we don't need to pass it when its false, remove from every calls where it is false. there are at several other places.
```suggestion
```

2024-01-25 07:23 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +    private async getPageObjectFromResults(item, emoji:boolean=false): Promise<IPage | null> {
As you are making changes in this file with suggestions, make a indentation with other methods too which has default value of emoji.
```suggestion
    private async getPageObjectFromResults(item, emoji:boolean = false): Promise<IPage | null> {
```

2024-01-25 07:25 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +            const nameWithoutEmoji = name.replace("📄", "");
we can avoid long variable name here.

```suggestion
            const { parent } = page;
            const { title } = prop;
            const name = page.name.replace("📄", "");
```

2024-01-25 07:28 UTC, Nabhag8848 requested changes
@brf153 Good work! Few More Changes, Hope those comments help you in future PRs.

2024-01-25 07:46 UTC, brf153 commented on src/handlers/ExecuteViewSubmitHandler.ts
> +        }
Yeah, that is better. I am making the changes.

2024-01-25 07:47 UTC, brf153 commented on src/helper/getSelectDatabaseLayout.ts
> +    const databaseNameWithoutEmoji = database_name.replace("📚 ", "")
My bad

2024-01-25 07:48 UTC, brf153 commented on src/lib/NotionSDK.ts
> +                false
Oki making the changes

2024-01-25 07:49 UTC, brf153 commented on src/lib/NotionSDK.ts
> +            const nameWithoutEmoji = name.replace("📄", "");
Oki

2024-01-25 08:01 UTC, brf153 commented
@Nabhag8848 Thank you for your detailed feedback and comments! I appreciate the guidance, and I'll make sure to incorporate these changes in my future PRs. Also, I have made the required changes.

2024-01-27 05:49 UTC, Nabhag8848 requested changes
Hey @brf153 remove console.log, and follow along other comments.

2024-01-27 05:49 UTC, Nabhag8848 commented on src/handlers/ExecuteViewSubmitHandler.ts
> +            console.log("databaseName ", databasename)
remove console.log
```suggestion
```

2024-01-27 05:49 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +    private returnPage(name: string, page_id: string, emoji: boolean=false): IPage {
```suggestion
    private returnPage(name: string, page_id: string, emoji: boolean = false): IPage {
```

2024-01-27 05:49 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +                name: name,
```suggestion
                name,
```

2024-01-27 07:31 UTC, brf153 commented
@Nabhag8848 made the changes

2024-01-28 17:44 UTC, Nabhag8848 approved these changes
LGTM @brf153 !!  🚀

2024-01-31 06:43 UTC, merged

2024-02-02 08:10 UTC, Spiral-Memory commented
Hey @brf153 , I am not sure what is causing it, but after this merge has been completed, I am noticing a thin line over the dropdown that is flickering while typing something. I'm not sure what is causing this issue. I saw your code, and I wasn't able to figure out what is causing the issue, so I am just letting you know that this is happening. If you can figure out what might be causing it, you can fix it. I tried reverting your changes and then that thin line disappeared, so i feel some changes might be causing this.  

![Screenshot from 2024-02-02 13-34-46](https://github.com/RocketChat/Apps.Notion/assets/78961432/96c3417b-05bf-4ff6-ae20-06bba7ecb721)

2024-02-02 08:57 UTC, brf153 commented
@Spiral-Memory I don't have it bro
![Screenshot from 2024-02-02 14-27-27](https://github.com/RocketChat/Apps.Notion/assets/107868772/5d44b2bf-0ea0-45f8-8c36-bf290b03f95c)

2024-02-02 09:05 UTC, Spiral-Memory commented
Can you check it in dark mode in the Microsoft edge browser ?