chore/ australian dollar support added
RocketChat/Apps.Notion pull request #45
Opened 2024-01-28 06:45 UTC by Sayan4444

## Proposed changes (including videos or screenshots)

CHANGES MADE

1. I have checked multiple formulas and they did give me correct answers, if there is any exception please do inform me
2. I have added support for Australian Dollars. 

## Issue(s)

This should close issues :-
fix #42 

## Steps to test or reproduce

 1. Check if the formula property works as expected in /notion create db. and make changes accordingly.
 2. as australian dollar has been supported now. under /notion create db if the Notion table includes a number then it should have a number format of australian dollar too.

## Further comments

2024-01-28 12:48 UTC, Sayan4444 commented
Hi @Nabhag8848 if I did any wrong or misunderstood something, please do inform me. I will love to rectify myself

2024-01-28 18:50 UTC, Nabhag8848 requested changes
Changes looks good, fixes the issue. added some comments have a look and also as this is small PR would you like to take up 
- #12 
and extend this. its beginner level and you could figure it out easily as i believe there is already similar code.

2024-01-28 18:50 UTC, Nabhag8848 commented on package-lock.json
Can you revoke this file changes in local and push again. currently we don't need to have updated lock file changes in main.

2024-01-28 18:50 UTC, Nabhag8848 commented on package.json
Question: is there any updates in apps engine ? cause as long as i believe we don't need to install @rocket.chat/ui-kit in dependecies to let uikit work.

2024-01-28 19:23 UTC, Sayan4444 commented on package.json
I have been facing error and npm deploy was not running

2024-01-28 19:28 UTC, Nabhag8848 commented on package.json
which version of RC you are using ?

2024-01-28 19:33 UTC, Sayan4444 commented on package-lock.json
Yes bhaiya I did it

2024-01-28 19:33 UTC, Sayan4444 commented on package.json
![image](https://github.com/RocketChat/Apps.Notion/assets/112304873/b27dfe2e-f2d2-403d-926b-aedd1d895645)

2024-01-28 19:42 UTC, Sayan4444 commented
> Changes looks good, fixes the issue. added some comments have a look and also as this is small PR would you like to take up
> 
> * [[Feat] Add Change Workspace Option in Overflow Menu within Create Page or Record Modal #12](https://github.com/RocketChat/Apps.Notion/issues/12)
>   and extend this. its beginner level and you could figure it out easily as i believe there is already similar code.

Sure, soon will start working in this issue

2024-01-29 04:57 UTC, Nabhag8848 commented
> > Changes looks good, fixes the issue. added some comments have a look and also as this is small PR would you like to take up
> > 
> > * [[Feat] Add Change Workspace Option in Overflow Menu within Create Page or Record Modal #12](https://github.com/RocketChat/Apps.Notion/issues/12)
> >   and extend this. its beginner level and you could figure it out easily as i believe there is already similar code.
> 
> Sure, soon will start working in this issue

LGTM, Lemme know if you have any questions around #12

2024-01-29 08:26 UTC, Sayan4444 commented
Yes @Nabhag8848 bhai I have a question. How can we track that the workspace has been opened from 'OverFlowComponent' and not from '/notion create db'. By using that only I will conditionally return the modal to 'pages create modal'

2024-02-04 19:29 UTC, merged

2024-02-04 19:31 UTC, Nabhag8848 commented
Thanks @Sayan4444 Good start! Congrats! Just letting you aware, as this is chore, won't be shown in gsoc leaderboard.