feat: added a overflow button to go to create subpage modal from create database modal
RocketChat/Apps.Notion pull request #48
Opened 2024-01-29 06:52 UTC by Spiral-Memory

Added a overflow button to go to "Create subpage or record modal" from "Create database" modal as there was no provision for that.

## Issue(s) 

Closes #47

## Acceptance Criteria fulfillment

- [x] Found out how to create an overflow menu using `OverflowMenuComponent.`
- [x] Investigated the process for adding new menu text and an Action ID, changed the `enum` file and `createDatabaseModal.ts` accordingly.
- [x] Implemented the overflow menu and handled the case in the handler when this "Create Subpage" menu is clicked.

## Proposed changes (including videos or screenshots)

https://github.com/RocketChat/Apps.Notion/assets/78961432/0e15b728-3fbb-4ae9-8bf3-d06982a7d691

## Further comments

2024-01-29 20:40 UTC, Spiral-Memory commented
@Nabhag8848 , as per your suggestion, I have added the "Change Workspace Overflow" button to the Create Database Modal, and the PR is now ready for review. I am also attaching the latest demo video for verification.

https://github.com/RocketChat/Apps.Notion/assets/78961432/7051f155-1b1d-4d25-af4f-af4b740992b9

2024-02-07 06:53 UTC, Nabhag8848 requested changes
Hey !  Added few comments and also can we have a functionality When switching to change workspace inside create database modal once the workspace has been changed can we move back and open up create database modal ? this way users can avoid writing command for opening the same modal of create database again. 
We need to Make sure this happens only when change workspace is open from create database Modal and not from regular /notion workspace.

2024-02-07 06:53 UTC, Nabhag8848 commented on enum/modals/NotionPageOrRecord.ts
> +    OVERFLOW_MENU_TEXT = "Create Subpage or Record",
we aren't specifying about page as subpage in app and we don't need to be explicit.
```suggestion
    OVERFLOW_MENU_TEXT = "Create Page or Record",
```

2024-02-07 06:53 UTC, Nabhag8848 commented on enum/modals/NotionPageOrRecord.ts
> +    OVERFLOW_MENU_TEXT = "Create Subpage or Record",
Can we make this more readable ? OVERFLOW_MENU_ACTION doesn't make it clear what this action id is for in overflow menu.

2024-02-07 07:29 UTC, Spiral-Memory commented on enum/modals/NotionPageOrRecord.ts
> +    OVERFLOW_MENU_TEXT = "Create Subpage or Record",
@Nabhag8848, I have raised a PR #62  in which I have made some terminology fixes. I have tried to be more specific and explicit throughout the entire project. I believe the current terminology may cause confusion for those using this integration for the first time. I also experienced confusion in the initial phase, which is why I attempted to be more specific here and in other places as well.

We have two options here: 
1. Be more specific everywhere to avoid confusion for first-time users.
2. If you feel that the existing terminology should be retained, I will remove the changes from both.

2024-02-07 07:29 UTC, Spiral-Memory commented on enum/modals/NotionPageOrRecord.ts
> +    OVERFLOW_MENU_TEXT = "Create Subpage or Record",
Sure @Nabhag8848 , Just a min let me do it

2024-02-07 07:32 UTC, Spiral-Memory commented
> Hey ! @Spiral-Memory Added few comments and also can we have a functionality When switching to change workspace inside create database modal once the workspace has been changed can we move back and open up create database modal ? this way users can avoid writing command for opening the same modal of create database again. We need to Make sure this happens only when change workspace is open from create database Modal and not from regular /notion workspace.
> 
> * @Sayan4444  has been working on similar thing [[Feat] Add Change Workspace Option in Overflow Menu within Create Pag… #49](https://github.com/RocketChat/Apps.Notion/pull/49) . check channel to see how it can be implemented you can collab if both the party agrees.

Sure @Nabhag8848 . I will review it and consider how it can be implemented. I will also discuss it with Sayan on that PR to see if both of us can collaborate. However, to prevent multiple people from resolving the same issue, I urge you to merge this PR. We can then work on the requested functionality together from that point onward.

2024-02-07 07:42 UTC, Spiral-Memory commented on enum/modals/NotionPageOrRecord.ts
> +    OVERFLOW_MENU_TEXT = "Create Subpage or Record",
Done

2024-02-07 14:14 UTC, Spiral-Memory commented
Hey, I tried implementing it. I am passing a state to keep track of whether it has been opened using the overflow button, and it is working. However, the problem I am facing is that as soon as the modal opens, it is closing automatically. I'm not sure why this is happening. Trying to debug. I will let you know about the progress.

2024-02-08 17:12 UTC, Nabhag8848 commented
> I feel that for Submit buttons which is passed as submit argument to openSurfaceView which executes ExecuteViewSubmitHandler once the button is clicked, clearing all the modals is a default behavior. I am not sure, but that might be the reason. Do you know of any way I can stop this behavior?
- Oops Yep ! This looks fine and its default behaviour and as far as i remember submit handler closes all the modal. Can you reach out to someone to ask if there is workaround for same that would be good exercise to know more about mindset around this behaviour of apps engine ?

2024-02-09 00:18 UTC, Spiral-Memory commented
Sure @Nabhag8848 , Will try asking more about it in the community. Also I'm going through the RC-engine repo to see if anything can be done.

2024-02-13 07:03 UTC, Nabhag8848 commented
@Spiral-Memory with the old implementation of uikit in github app reopening of the modals can be achieved on Submit Action, Right ?

2024-02-13 07:20 UTC, Spiral-Memory commented
> @Spiral-Memory with the old implementation of uikit like in github app reopening of the modals can be achieved on Submit Action, Right ? 

Yes, @Nabhag8848 ,there is a function called `openModalViewResponse` that I have seen in the GitHub app code. With that, I feel it can be achieved. The function accepts `IUKitModalViewParam` and not the surface one.

2024-02-13 07:34 UTC, Nabhag8848 commented
> > @Spiral-Memory with the old implementation of uikit like in github app reopening of the modals can be achieved on Submit Action, Right ?
> 
> Yes, @Nabhag8848 ,there is a function called `openModalViewResponse` that I have seen in the GitHub app code. With that, I feel it can be achieved. The function accepts `IUKitModalViewParam` and not the surface one.

if thats the case, Ask and Tag Devanshu in Apps-Development Was there changes in new UI Kit on how modals are handled ? cause this potentially may not be not expected behaviour, if same can be achieved with old ui kit implementation. (Submit Action) + verify it yourself by spinning new app and implementing this with old UI before doing that.

Note that: Button as a Action or within Section in Modals can achieve this already but we are talking about Submit Action

2024-02-13 07:40 UTC, Spiral-Memory commented
> > > @Spiral-Memory with the old implementation of uikit like in github app reopening of the modals can be achieved on Submit Action, Right ?
> > 
> > Yes, @Nabhag8848 ,there is a function called `openModalViewResponse` that I have seen in the GitHub app code. With that, I feel it can be achieved. The function accepts `IUKitModalViewParam` and not the surface one.
> 
> @Spiral-Memory if thats the case, Ask and Tag Devanshu in Apps-Development Was there changes in new UI Kit on how modals are handled ? cause this potentially may not be not expected behaviour, if same can be achieved with old ui kit implementation. (Submit Action) + verify it yourself by spinning new app and implementing this with old UI before doing that.
> 
> Note that: Button as a Action or within Section in Modals can achieve this already but we are talking about Submit Action

Sure, @Nabhag8848 , I will try creating a new app and testing all possible behaviors of both older and newer implementations. Also, I will tag Devanshu and ask as well.

And yeah, I know that using a button as an action or within a section can be achieved; I have tried that, and it was working. The issue arises with "Submit" as an action. It abruptly closes all modals, even though the other modal opens for a second.

2024-02-13 07:47 UTC, Spiral-Memory commented
Also, @Nabhag8848 , is there documentation that clearly states all such behaviors or how it works? Currently, the website has very basic documentation, and the list of functions on the website doesn't explain the functionality of everything. Is there proper documentation available to help understand RC app development in a much better way?

2024-02-13 07:51 UTC, Sayan4444 commented
Yes there is all the function definitions are found here @Spiral-Memory 
https://rocketchat.github.io/Rocket.Chat.Apps-engine/interfaces/accessors_IMessageExtender.IMessageExtender.html#addAttachment

2024-02-13 19:25 UTC, Spiral-Memory commented
> Yes there is all the function definitions are found here @Spiral-Memory 
> https://rocketchat.github.io/Rocket.Chat.Apps-engine/interfaces/accessors_IMessageExtender.IMessageExtender.html#addAttachment

I'm aware of this, @Sayan4444 , but it doesn't give enough examples to understand how everything works. I'm looking for something that provides more information, more like an index of functions with very brief descriptions.

2024-02-15 15:28 UTC, Spiral-Memory commented
Hey @Nabhag8848 , just to update you, I've contacted Devanshu. He mentioned he will look into the issue, determine why we're experiencing unexpected behavior, and will let us know.

2024-02-20 14:44 UTC, Nabhag8848 commented
> Hey @Nabhag8848 , just to update you, I've contacted Devanshu. He mentioned he will look into the issue, determine why we're experiencing unexpected behavior, and will let us know.

- Awesome ! maybe if once your exams are finished you can try to find out the issue yourself.

2024-02-27 13:02 UTC, Spiral-Memory commented
Hey @Nabhag8848 , I went through the RC engine repo and tried building the RC app, but I still can't find the problem. So, for now, I feel we should stick to halting the "going back" feature and focus on other issues. Also, please review this and other PRs whenever you are free. If I find anything related to this particular feature, I'll let you know sir.

@Sayan4444 , did you find a fix for it?

2024-02-27 13:59 UTC, Sayan4444 commented
@Spiral-Memory No I tried a lot

2024-02-27 15:11 UTC, Spiral-Memory commented
> @Spiral-Memory No I tried a lot

Same 🥲

2024-02-29 08:44 UTC, Nabhag8848 commented
> Hey @Nabhag8848 , I went through the RC engine repo and tried building the RC app, but I still can't find the problem. So, for now, I feel we should stick to halting the "going back" feature and focus on other issues. Also, please review this and other PRs whenever you are free. If I find anything related to this particular feature, I'll let you know sir.
> 
> @Sayan4444 , did you find a fix for it?

Thanks @Spiral-Memory @Sayan4444 thats sounds cool to me for now. Will merge this and review all leftover PRs. just stuck with some of my deadlines. Will do it today at night🙏🏻

2024-02-29 08:47 UTC, Spiral-Memory commented
> > Hey @Nabhag8848 , I went through the RC engine repo and tried building the RC app, but I still can't find the problem. So, for now, I feel we should stick to halting the "going back" feature and focus on other issues. Also, please review this and other PRs whenever you are free. If I find anything related to this particular feature, I'll let you know sir.
> > 
> > @Sayan4444 , did you find a fix for it?
> 
> Thanks @Spiral-Memory @Sayan4444 thats sounds cool to me for now. Will merge this and review all leftover PRs. just stuck with some of my deadlines. Will do it today at night🙏🏻 

Sure @Nabhag8848 Sir. Thanks a lot 😃

2024-02-29 08:49 UTC, Sayan4444 commented
> > Hey @Nabhag8848 , I went through the RC engine repo and tried building the RC app, but I still can't find the problem. So, for now, I feel we should stick to halting the "going back" feature and focus on other issues. Also, please review this and other PRs whenever you are free. If I find anything related to this particular feature, I'll let you know sir.
> > @Sayan4444 , did you find a fix for it?
> 
> Thanks @Spiral-Memory @Sayan4444 thats sounds cool to me for now. Will merge this and review all leftover PRs. just stuck with some of my deadlines. Will do it today at night🙏🏻

Thanks bhaiya for giving me the chance to help

2024-02-29 14:08 UTC, Nabhag8848 commented on enum/modals/NotionPageOrRecord.ts
> +    OVERFLOW_MENU_TEXT = "Create Subpage or Record",
@Spiral-Memory You are right but lets make that change in that PR. Cause We will get the Suggestion about this (if needed) when submiting app for review to team. 
- For Now :  Just have `Page`

2024-02-29 14:09 UTC, Nabhag8848 commented on enum/modals/NotionPageOrRecord.ts
> +    OVERFLOW_MENU_TEXT = "Create Subpage or Record",
@Spiral-Memory Lemme know once you done. We can merge, Else Everything LGTM !

2024-02-29 14:13 UTC, Nabhag8848 commented on enum/modals/NotionPageOrRecord.ts
> +    OVERFLOW_MENU_TEXT = "Create Subpage or Record",
@Spiral-Memory oops i meant `Create Page or Record` as mentioned above.

2024-02-29 14:16 UTC, Spiral-Memory commented on enum/modals/NotionPageOrRecord.ts
> +    OVERFLOW_MENU_TEXT = "Create Subpage or Record",
@Nabhag8848 , Sorry for the mistake, now done

2024-02-29 14:21 UTC, merged

2024-02-29 14:24 UTC, Nabhag8848 commented
Congrats @Spiral-Memory ! Hope you loved going depth on researching about issues in apps engine. 
- The amount of satisfaction you get when PR getting merged after so much work is unmatchable, it reminds me of my pre gsoc season.
-  Also Great Collab with @Sayan4444 🚀

2024-02-29 14:42 UTC, Spiral-Memory commented
> Congrats @Spiral-Memory ! Hope you loved going depth on researching about issues in apps engine. 
> - The amount of satisfaction you get when PR getting merged after so much work is unmatchable, it reminds me of my pre gsoc season.
> -  Also Great Collab with @Sayan4444 🚀

No doubt, @Nabhag8848 , it was a wonderful experience going through the engine repo and trying to build the app from scratch. It helped me learn as well. Yes, I can resonate with the feelings you had during your time at GSoC. Also, thank you so much for the appreciation and your guidance. I will continue to look into this feature, and if I see any improvement, I will let you know as well.