[Feat] Add Change Workspace Option in Overflow Menu within Create Pag…
RocketChat/Apps.Notion pull request #49
Opened 2024-01-29 14:06 UTC by Sayan4444

## Proposed changes (including videos or screenshots)

CHANGES MADE

 1. Ability to navigate to create database and change workspace modals from create page modal

## Issue(s)

This should close issues :-
fix #12 

## Steps to test or reproduce

https://github.com/RocketChat/Apps.Notion/assets/112304873/2ac39ecf-174a-4ea4-b4ad-de83aa527d9a

## NOT IMPLEMENTED

-->after the workspace has been changed Open the Create Database Modal Again, By Default

I need further guidance to implement this feature

2024-02-07 06:58 UTC, Nabhag8848 commented
@Sayan4444 were you able to implement:  changed to Create Page or Database Modal Again once you change workspace from it?

2024-02-07 07:22 UTC, Sayan4444 commented
@Nabhag8848 Not yet but almost to it will be raising a PR very soon. Spent the last few days understanding how apps-engine works so that I can tackle any future problems

2024-02-07 07:56 UTC, Spiral-Memory commented
Hey @Sayan4444 , since you've been working on this for some time, specifically going back to the modal once the workspace is changed, the same feature needs to be implemented for Create Database modal also as in PR #48. Can we collaborate on this? I'm also interested in hearing your observations and thoughts on how this can be done, given your efforts to solve it for a while.

2024-02-07 08:02 UTC, Sayan4444 commented
@Spiral-Memory sure....I will be telling you the details by night

2024-02-07 18:15 UTC, Spiral-Memory commented
Hey @Sayan4444 , I have the state passing and have tried solving it and its working also, the problem is after the modal opens, it closes abruptly within a second, looks like this is a default behavior of Submit button. Have you figured out a way ? If yes, please let me know. Also go through my PR #48, i have attached a video, once see and let me know if there is a way to fix it.

2024-02-07 20:10 UTC, Sayan4444 commented
@Spiral-Memory can you tell me how can u passing the states? Moreover how can u opening the modal on save?....I have also managed to pass the state but its not opening themmodal....you can also push your code in this or another branch

2024-02-07 21:21 UTC, Spiral-Memory commented
Use the same approach as in ExecuteActionBlockHandler

Create a handler object using `new Handler` after importing the handler.

Then, use `await handler.xyz()`.

Sure, I will push it tomorrow.

2024-02-08 01:51 UTC, Sayan4444 commented
Actually @Spiral-Memory I have worked for the "Cancel" button redirection. When we create a instance of handler it need things like "room","triggeredId" which is absent in ExecuteCloseButton. Even if u pass it via Modal Storage from ExecuteActionBlockHandler, it wont work for some reason

2024-02-08 01:51 UTC, Sayan4444 commented
@Spiral-Memory how about we have a voice call somehow, any time free after 6pm today?

2024-02-08 06:43 UTC, Sayan4444 commented
@Spiral-Memory do tell me when you are free

2024-02-08 15:15 UTC, Sayan4444 commented
https://youtu.be/9o4Nx7Ho_hA

@Nabhag8848  I have been able to change state, but it closes automatically(modal shows as long as handler.createNotionPageOrRecord). I cant find out why! maybe its the default behavior of "Submit" button or something is getting cleared, making the modal close. If you want I can push the commit till the progress I have been able to make.
Debugging tried:- removed everything that clears any state but still same behavior

2024-02-08 15:19 UTC, Spiral-Memory commented
> https://youtu.be/9o4Nx7Ho_hA
> 
> @Nabhag8848  I have been able to change state, but it closes automatically(modal shows as long as handler.createNotionPageOrRecord). I cant find out why! maybe its the default behavior of "Submit" button or something is getting cleared, making the modal close. If you want I can push the commit till the progress I have been able to make.
> Debugging tried:- removed everything that clears any state but still same behavior

Exactly, i am facing the same issue.. i also have a feeling that it is the default behaviour of the Submit button to clear everything at the end. I went through the Rc Engine repo to understand if anything can be done. There are some props it takes, notifyOnClose or canClose kind of parameters but i am unable to figure out what exactly it does.

2024-02-08 15:23 UTC, Spiral-Memory commented
If you make any progress or figure out the way, let me know. I am also trying my best to figure out how it can be done.

2024-02-08 15:52 UTC, Sayan4444 commented
@Spiral-Memory if you have time try out these two things
1. Since there are a lot of repos in using apps engine...try to setup and see its working
2. Setup a apps-engine project from scratch and replicate the issue and try to solve it
I have my exams soon and having very less time.....aap thora explore kijie and do keep me updated

2024-02-08 15:53 UTC, Spiral-Memory commented
Yep, I am exploring other RC repos to see if anywhere it is implemented. By the way 😂, I am also having exams only. We are in the same stage.

2024-02-20 13:36 UTC, Sayan4444 commented
@Spiral-Memory any update regarding this issue?

2024-02-20 13:51 UTC, Spiral-Memory commented
No, bro, currently busy with midterms; will soon look into it again.

2024-02-29 14:25 UTC, Nabhag8848 commented
@Sayan4444 Can you solve the conflicts and rebase your PR, this happened as i just merged @Spiral-Memory PR?

2024-02-29 19:10 UTC, Sayan4444 commented
@Nabhag8848 I have resolved all the merge conflicts

2024-02-29 19:57 UTC, Nabhag8848 commented
> @Nabhag8848 I have resolved all the merge conflicts

@Sayan4444 there are override changes,  no code should get removed or commented and it should include all the latest code you had.  

- maybe Checkout some blogs on Rebase and Solving Conflicts.

2024-02-29 20:14 UTC, Spiral-Memory commented
@Nabhag8848 , I think he have rebased it correctly, its just that's after rebasing, he also changed his code since he was using duplicate variable for same so he removed it and added the same change in this commit itself.

2024-03-01 14:48 UTC, Nabhag8848 commented
> > @Nabhag8848 , I think he have rebased it correctly, its just that's after rebasing, he also changed his code since he was using duplicate variable for same thing, so he removed it and added that change also along with rebasing in this commit itself.
> 
> Yep. @Sayan4444 revert back your change. and again rebase and solve the conflicts properly.
> 
> Starting point would be to `git reflog`

@Sayan4444 let us know if need any help around doing that. 

- Just revert your last commit - merge conflicts commit. Solve the merge conflict again carefully and push the changes again.

2024-03-01 15:01 UTC, Sayan4444 commented
Sure @Nabhag8848 . Had a very busy day will sit at night and complete it

2024-03-01 18:18 UTC, Sayan4444 commented
Hi @Nabhag8848 , can you check if I did correct this time?

2024-03-01 19:07 UTC, Nabhag8848 requested changes
@Sayan4444 Added few comments, lemme know once you done, also please check once entirely and make sure everything works fine and nothing is breaking in this case.

2024-03-01 19:07 UTC, Nabhag8848 commented on src/modals/createPageOrRecordModal.ts
> +    ];
Here, When Database is Selected, We are getting the Option of Change Workspace in between, Can we make sure that option `Change Workspace` gets at the end, after Change Database. 

```
In this Order: 
 Create Database
 Change Database
 Change Workspace
```

<img width="428" alt="Change" src="https://github.com/RocketChat/Apps.Notion/assets/65061890/fe0970fd-1cfa-4782-9b46-d6bff2bbe790">

2024-03-01 19:07 UTC, Nabhag8848 commented on src/handlers/ExecuteBlockActionHandler.ts
> -
Add a Vertical Space over  here as it was to maintain the Readablitiy of Code.

2024-03-01 19:11 UTC, Spiral-Memory commented
@Sayan4444 , there are three cases in which you could test if everything is working fine:

1. From the Create Page or Record Modal, it should navigate to Create Database and Change Workspace.

2. From the Create Database Modal, it should perform both actions as well.

3. In the Create Page or Record Modal, select a database in the select box; it will update the modal. There must be three overflow lists: Change Database, Create Database, and Change Workspace (ensure they appear in this order).

Also, for your help, I have sent you a zip file on LinkedIn in which I have rebased and made the changes to make everything work. You can review that too if you need any help. If you need any help, please let me know

2024-03-01 19:14 UTC, Spiral-Memory commented on src/modals/createPageOrRecordModal.ts
> +    ];
@Nabhag8848 , I feel it will be better if it appear in Change Database then Create Database and then Change Workspace, Because Change database is closely related to that modal itself, as it will update the same modal. What do you think ?

2024-03-01 19:18 UTC, Nabhag8848 commented on src/modals/createPageOrRecordModal.ts
> +    ];
@Spiral-Memory Thanks for the Input ! + That will look more natural  (As we already have Create Database and Change Workspace option)+ more often that is the option which user will need to use. 

When selecting only that option will get added to top of overflow. Sounds Cool to me.

2024-03-01 19:24 UTC, Spiral-Memory commented on src/modals/createPageOrRecordModal.ts
> +    ];
Exactly @Nabhag8848 !,  For that, @Sayan4444 you can create an empty array first, then if(parent) is available, add "Change Database", after that append other two options in the array. You can also check my implementation I sent.

2024-03-01 20:28 UTC, Sayan4444 commented on src/modals/createPageOrRecordModal.ts
> +    ];
@Spiral-Memory kept the code same just used the unshift method to put the element at first

2024-03-01 20:32 UTC, Sayan4444 commented
@Nabhag8848 bhaiya I have resolved all the requested changes

2024-03-01 20:38 UTC, Spiral-Memory commented on src/modals/createPageOrRecordModal.ts
> +    ];
Yep, that's a better approach 🚀

2024-03-01 20:44 UTC, Sayan4444 commented
https://www.youtube.com/watch?v=pnZBoe1NAGU

2024-03-03 06:46 UTC, Nabhag8848 commented on src/modals/createPageOrRecordModal.ts
> +    ];
Awesome @Sayan4444 🔥

2024-03-03 06:50 UTC, Nabhag8848 approved these changes
LGTM ! 🔥 @Sayan4444

2024-03-03 07:01 UTC, merged

2026-10-25 08:01 UTC, zamorayami17-hash approved these changes