fix: adding changes to remove line breaks
RocketChat/Apps.Notion pull request #54
Opened 2024-01-30 06:55 UTC by brf153

## Issue(s) 

closes #46 

## Proposed changes (including videos or screenshots)
![Screenshot from 2024-01-30 12-09-00](https://github.com/RocketChat/Apps.Notion/assets/107868772/c36979a0-a375-408f-9edf-9d03b7b8eeba)

2024-01-31 15:29 UTC, brf153 commented
@Nabhag8848 shall I change the other buttons also?

2024-02-06 05:29 UTC, brf153 commented
@Nabhag8848 I have made the required changes.
![Screenshot from 2024-02-06 10-58-54](https://github.com/RocketChat/Apps.Notion/assets/107868772/a2817db5-9daa-41eb-ad4d-f58ec0409e29)

2024-02-13 05:02 UTC, Nabhag8848 commented
Hey @brf153 Can you rebase and merge to your branch, correctly. Your Changes include emojis which you removed earlier in PR and you shouldn't include it. You can head over to Git Repo to know about rebase practices.

2024-02-13 05:52 UTC, brf153 commented
> Hey @brf153 Can you rebase and merge to your branch, correctly. Your Changes include emojis which you removed earlier in PR and you shouldn't include it. You can head over to Git Repo to know about rebase practices.

Sorry for the mistake @Nabhag8848. I have fixed it. I had to remove emojis from onInstallContent as well. I have done it.

2024-02-29 17:28 UTC, Nabhag8848 requested changes
Hey @brf153 Just some changes. Lemme know once you done. We can merge this one. Thank you so much for this one.

2024-02-29 17:28 UTC, Nabhag8848 commented on src/helper/message.ts
>      }** ! ${OnInstallContent.WELCOME_TEXT.toString()}`;
@brf153 
const text = ` Hey **${user.username}** ! ${OnInstallContent.WELCOME_TEXT.toString()} ${OnInstallContent.WELCOMING_MESSAGE.toString()}`;

Instead of combinedText, can we have this full text `oneline`. for some reason here in markdown of github it isn't getting in oneline. 

- Also Remove Emoji. 

Else Everything LGTM! Lemme know once you done so we can merge this.

2024-02-29 17:28 UTC, Nabhag8848 commented on src/helper/message.ts
> +    const combinedText = `${text} ${OnInstallContent.WELCOMING_MESSAGE.toString()}`;
```suggestion
```

as we will have this merge in text variable.

2024-03-01 04:49 UTC, brf153 commented
@Nabhag8848 done

2024-03-01 09:32 UTC, merged