[Feat]: Introducing Pagination Support for Notion API in Page and Database Responses
RocketChat/Apps.Notion pull request #59
Opened 2024-01-31 17:08 UTC by brf153

## Issue(s) 

closes #38 

## Acceptance Criteria fulfillment

- [x] Check how the pagination is working in the api
- [x] Make changes to searchPage and searchDatabase methods.

## Proposed changes (including videos or screenshots):
Made changes to searchPage method. Now, we are getting all the pages made in a workspace.
__Screenshot of the length of the final results after concatenating all the response.data.results__
![Screenshot from 2024-01-21 21-36-14](https://github.com/RocketChat/Apps.Notion/assets/107868772/805666b6-3741-46b9-bdc9-47b04611b7e2)

2024-01-31 17:09 UTC, brf153 commented
@Nabhag8848I have resolved the merge conflicts, but unfortunately, I mistakenly force-pushed the changes, leading to the dissolution of my previous pull request. However, upon further inspection, I can confirm that the changes are still present.

2024-01-31 17:11 UTC, brf153 commented
## The Changes

https://github.com/RocketChat/Apps.Notion/assets/107868772/b02089d4-be7d-4584-9e90-fbc2ff4d5858


https://github.com/RocketChat/Apps.Notion/assets/107868772/1a97f9a3-93e3-4044-9a00-2e198ed18f15


https://github.com/RocketChat/Apps.Notion/assets/107868772/22fa303e-bab1-4131-bbdd-1ca8a2a3122d

2024-03-09 06:18 UTC, Nabhag8848 commented
@brf153 Reviewing this right now, Sorry for So much delay on this. 🙏🏻

2024-03-09 13:46 UTC, brf153 commented
@Nabhag8848 No problem at all! I appreciate you getting back to me. Take your time with the review, and let me know if there are any further changes required. Looking forward to hearing your thoughts!

2024-03-09 18:49 UTC, Nabhag8848 requested changes
@brf153 Added examples and comments for changes, lemme know once you are done, will ASAP review back.

2024-03-09 18:49 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +
```suggestion
```

```
- Better Approach: 

 public async searchPages(
        token: string,
        cursor: string = "init" <- In the code you implement please have this in ENUM
    ): Promise<Array<IPage> | Error> {
        const isInit = cursor == "init"; <- Use the above enum you already will have.
        try {
            const data = {
                filter: {
                    value: NotionObjectTypes.PAGE,
                    property: NotionObjectTypes.PROPERTY,
                },
                start_cursor: !isInit ? cursor : undefined,
            };

            const response = await this.http.post(NotionApi.SEARCH, {
                data,
                headers: {
                    Authorization: `Bearer ${token}`,
                    "Content-Type": NotionApi.CONTENT_TYPE,
                    "User-Agent": NotionApi.USER_AGENT,
                    "Notion-Version": this.NotionVersion,
                },
            });
            if (!response.statusCode.toString().startsWith("2")) {
                return this.handleErrorResponse(
                    response.statusCode,
                    `Error While Searching Pages: `,
                    response.content
                );
            }

            const { results, next_cursor, has_more } = response.data;
            if (has_more === true && cursor) {
                const recursiveResults = await this.searchPages(
                    token,
                    next_cursor
                );

                if (recursiveResults instanceof Error) {
                    return recursiveResults;
                }

                results.push(...recursiveResults);
            }

            if (!isInit) return results;

            const result: Array<IPage> = [];
            results.forEach(async (item) => {
                const pageObject = await this.getPageObjectFromResults(item);
                if (pageObject) {
                    result.push(pageObject);
                }
            })
            return result;
        } catch (err) {
            throw new AppsEngineException(err as string);
        }
    }

```

- Hey @brf153 Can't we have instead implement recursion without using the helper extra function. similar to above, can we change `THIS ONE and REST OF THE Implementation USING this apporach` make sure we don't need to use extra method and avoid having duplicacy of code.


- Also make sure about this case what if during the paginated requests one of the requests get error from server in that case we need to assume that whole request is Error. above example solves that. Your implementation doesn't include that.

- lets use forEach loops and lets stick to code already have to maintain consistency.


Also there is a bug in getPageObjectFromResults: 

```

private async getPageObjectFromResults(
        item,
        emoji: boolean = false
    ): Promise<IPage | null> {
        const typesWithTitleProperty = [
            NotionObjectTypes.WORKSPACE.toString(),
            NotionObjectTypes.PAGE_ID.toString(),
        ];
        const parentType: string = item.parent.type;
        const properties = item.properties;
        const pageId: string = item.id;

        if (typesWithTitleProperty.includes(parentType)) {
            const pageName: string =
                properties.title.title[0]?.text?.content ||
                NotionObjectTypes.UNTITLED;
            return this.returnPage(pageName, pageId, emoji);
        }

        // title property either be at first or last position
        const columns = Object.keys(properties);
        const firstColumn = columns[0];
        const lastColumn = columns[columns.length - 1];

        // title at first position and has subpage
        if (properties[firstColumn].title) { <- Removed the length statement here this is updated version, remove in your PR code as well
            const name: string =
                properties[firstColumn].title[0]?.text?.content ||
                NotionObjectTypes.UNTITLED;
            return this.returnPage(name, pageId, emoji);
        }

        //title at last position and has subpage
        if (properties[lastColumn].title) { <- Removed the length statement here this is updated version as well.
            const name: string =
                properties[lastColumn].title[0]?.text?.content ||
                NotionObjectTypes.UNTITLED;
            return this.returnPage(name, pageId, emoji);
        }

        return null;
    }


```

- So when we get the page from the api: we need to make sure we get all the pages, removing that length statement solves the Untitled pages not being shown:
1.  parent page
2.  sub pages
3. database row (this are also the pages)
4. page without titled should get `Untitled` title

If you currently will request there are `140` pages, in your workspace you shared

2024-03-09 18:49 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +
- As you have Introduce this method, Lets change in entire file, where we are passing this exact same header and lets make the lines of code less and call this method instead of hard coding

- INCLUDING the code changes i shared.

```
Eg: 
 const response = await this.http.post(NotionApi.SEARCH, {
        headers: this.getNotionApiHeaders(token)
 });
```

2024-03-09 18:49 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +
- Implement making sure We have just one method and don't have extra helper method to avoid duplicacy as approached shared above. 

- Also make sure about this case what if during the paginated requests one of the requests get error from server in that case we need to assume that whole request is Error. above example solves that.

- Applies to all three: searchDatabases, searchPages, searchPagesAndDatabases

2024-03-09 18:49 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> -    public async searchPagesAndDatabases(
- Change according to approach similar to shared.

- Also make sure about this case what if during the paginated requests one of the requests get error from server in that case we need to assume that whole request is Error. above example solves that.

2024-03-09 18:49 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +
- You can use conditional statments in object instead of making if else statement. implement in new implementation according to code example shared.

2024-03-09 18:49 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +                throw new AppsEngineException(`Error While Searching Databases: ${response.content}`);
```suggestion
                return this.handleErrorResponse(
                    response.statusCode,
                    `Error While Searching Databases: `,
                    response.content
                );
```

-  never throw an error for an usual error response, we are handling this error to later don't open a modal if we don't get the database

2024-04-03 04:58 UTC, brf153 commented
@Nabhag8848 working on this. Sorry for the delay

2024-04-04 17:17 UTC, Nabhag8848 commented
> @Nabhag8848 working on this. Sorry for the delay

No Worries, Thanks ! Looking forward 🚀

2024-04-06 03:23 UTC, brf153 commented
@Nabhag8848 I have made the changes, and your suggestions have greatly helped me. Thank you for the recommendations.

2024-04-06 15:39 UTC, Nabhag8848 commented
> @Nabhag8848 I have made the changes, and your suggestions have greatly helped me. Thank you for the recommendations.

@brf153 🙏 will review it, by tomorrow thanks!

2024-04-08 07:40 UTC, Nabhag8848 requested changes
Hey @brf153 Added some comments, few more Changes, we can merge this after. Lemme know once you are done. 

Thanks !

2024-04-08 09:41 UTC, brf153 commented
@Nabhag8848 made the changes

2024-04-08 10:40 UTC, Nabhag8848 approved these changes
LGTM 🔥 @brf153  Very Thanks

2024-04-08 10:45 UTC, merged