[Feat] Improve readability of comment created time
RocketChat/Apps.Notion pull request #73
Opened 2024-03-12 01:22 UTC by JeffreytheCoder

## Issue(s) 

Closes #72 

## Acceptance Criteria fulfillment

- [ ] Convert comment created time from ISO to relative time

## Proposed changes (including videos or screenshots)

![notion-time](https://github.com/RocketChat/Apps.Notion/assets/35394596/4300c3b3-90f7-4f1a-92ea-5eeeb0f8b5db)

2024-03-12 06:44 UTC, Nabhag8848 requested changes
Hey @JeffreytheCoder Added few comments for change. Lemme know once its done.

2024-03-12 06:44 UTC, Nabhag8848 commented on src/helper/getTimeAgoFromISO.ts
> +}
```suggestion
    if (secondsAgo < 60) {
        return "Just now";
    }
    if (minutesAgo < 60) {
        return `${minutesAgo} minutes ago`;
    }
    if (hoursAgo < 24) {
        return `${hoursAgo} hours ago`;
    }
    if (daysAgo === 1) {
        return "yesterday";
    }
    if (daysAgo < 7) {
        return `${daysAgo} days ago`;
    }
    if (daysAgo === 7) {
        return "1 week ago";
    } 
    
    // for dates more than 7 days ago, give a precise date
    const fullFormatter = new Intl.DateTimeFormat("en-US", {
         year: "numeric",
         month: "long",
         day: "numeric",
    });
   
    return fullFormatter.format(date);
}
```
- Great usecase: not using else for better readability.

2024-03-12 06:44 UTC, Nabhag8848 commented on src/modals/createCommentContextualBar.ts
> +            const userName = `**${commentInfo.user.name}** ${formattedTime}`;
- This makes unneccassary calls for formatting time, everytime when comment is created, which we can avoid. 

- We are Caching the comments when page is selected, at same time we retrieve comments and store in persistance storage. 

- when we update the Contextual bar during creation of comment we are using cached comments and unshift ( add new comment to zeroth index) and update the cache.

- So We will need to format `created_time` in api layer instead, check reference below:

https://github.com/RocketChat/Apps.Notion/blob/main/src/lib/NotionSDK.ts#L440-L493
https://github.com/RocketChat/Apps.Notion/blob/main/src/lib/NotionSDK.ts#L295

2024-03-12 06:50 UTC, JeffreytheCoder commented on src/helper/getTimeAgoFromISO.ts
> +}
good catch!

2024-03-12 07:00 UTC, JeffreytheCoder commented on src/modals/createCommentContextualBar.ts
> +            const userName = `**${commentInfo.user.name}** ${formattedTime}`;
I added the time formating in the modal, only for display, because I wanted to leave the API layer unchanged in case we need the precise time for other purposed. Are you sure we want to just return the formatted time from the API?

2024-03-12 07:02 UTC, JeffreytheCoder commented on src/modals/createCommentContextualBar.ts
> +            const userName = `**${commentInfo.user.name}** ${formattedTime}`;
Also the time is relative to the user's current time so it changes every time...not sure if the caching will work

2024-03-12 07:18 UTC, Nabhag8848 commented on src/modals/createCommentContextualBar.ts
> +            const userName = `**${commentInfo.user.name}** ${formattedTime}`;
@JeffreytheCoder 
We are caching just within lifecycle of Contextual bar and clearing that cache when Contextualbar is closed, also, if there is left over cache due to some unexpected behaviours, network failure during lifecycle we are clearing the cache when contextual bar is opened. 

We are doing this inorder to improve the performance of App,  Everytime retriving the Comments, when updating the Contextual bar won't be feasible, in a way how Apps Engine works and  allows us to do certain things and also response from notion do take time for comments. think it assuming if there are more than 100 comments.

Check this method: https://github.com/RocketChat/Apps.Notion/blob/main/src/handlers/ExecuteBlockActionHandler.ts#L598

Right here updating in persistance storage, with new comment: 
https://github.com/RocketChat/Apps.Notion/blob/main/src/handlers/ExecuteBlockActionHandler.ts#L666

Accessing Comments from Lifecycle Cache: 
https://github.com/RocketChat/Apps.Notion/blob/main/src/handlers/ExecuteBlockActionHandler.ts#L666

2024-03-12 19:01 UTC, JeffreytheCoder commented on src/modals/createCommentContextualBar.ts
> +            const userName = `**${commentInfo.user.name}** ${formattedTime}`;
Thanks for explaining this! I've moved time formatting to API to utilize cache

2024-03-14 21:35 UTC, JeffreytheCoder commented
@Nabhag8848 Added the changes you mentioned. Ready for review

2024-03-18 09:27 UTC, Nabhag8848 approved these changes
LGTM @JeffreytheCoder ! will merge oncel, we test on my end.

2024-03-23 06:21 UTC, JeffreytheCoder commented
@Nabhag8848 Thanks for the suggestion! Just created an issue #75 and I'm working on it. 

How's the testing of this PR on your side?

2024-03-23 11:52 UTC, merged

2024-03-23 11:53 UTC, Nabhag8848 commented
> @Nabhag8848 Thanks for the suggestion! Just created an issue #75 and I'm working on it.
> 
> How's the testing of this PR on your side?

Merged 🚀 @JeffreytheCoder Thanks ! 

Thats Awesome !