fix: pagination support for fetching comments
RocketChat/Apps.Notion pull request #76
Opened 2024-04-09 06:13 UTC by JeffreytheCoder

## Issue(s) 

Closes #75 

## Proposed changes (including videos or screenshots)

![paginated-comments](https://github.com/RocketChat/Apps.Notion/assets/35394596/18a1d972-0a37-4b5e-9a2a-b4c9f1893d44)

2024-04-09 12:08 UTC, Nabhag8848 requested changes
Hey @JeffreytheCoder Added one comment, lemme know once you are done, we can merge this. Thanks !

2024-04-09 12:08 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +
```suggestion
```

Hey @JeffreytheCoder instead of changing JSON with condition in order to match a type, this is a good case to use  short circuiting.

2024-04-09 12:08 UTC, Nabhag8848 commented on src/lib/NotionSDK.ts
> +                params,
@JeffreytheCoder  Something like this. 
```suggestion
      params: {
         block_id: pageId,
         ...(cursor && { start_cursor: cursor }),            
      }
```

2024-04-09 18:22 UTC, JeffreytheCoder commented
> Hey @JeffreytheCoder Added one comment, lemme know once you are done, we can merge this. Thanks !

Good catch! Added the change

2024-04-10 01:34 UTC, Nabhag8848 approved these changes
LGTM 🔥 @JeffreytheCoder  !

2024-04-10 01:37 UTC, merged